CREATE TABLE Users (
    UserId INT IDENTITY(1,1) PRIMARY KEY,
    FirstName NVARCHAR(50) NOT NULL,
    LastName NVARCHAR(50) NOT NULL,
    Username NVARCHAR(50) UNIQUE NOT NULL,
    PasswordHash NVARCHAR(255) NOT NULL,
    Department NVARCHAR(50) NOT NULL,
    Position NVARCHAR(50) NOT NULL,
	photoUrl NVARCHAR(500) NOT NULL
);